---
title: "Optical properties of water for prediction of wastewater contamination in surface water"
author: "Steven R. Corsi^1^, Laura A. De Cicco^1^, Angela Hanson^2^, Peter Lenaker^1^, Brian Bergamaschi^2^, Brian Pellerin^3^"
date: ""
#output: word_document
output:
  bookdown::word_document2:
#    css: environmental-science-and-technology.csl
    fig_caption: yes
    toc: no
    reference_docx: "word-styles-reference-orig.docx"
#bibliography: Optical properties.bib
#link-citations: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
knitr::opts_knit$set(root.dir = '../../') 
```

```{r some_resources, echo=FALSE}


# Resources: 
# Commonly used symbols in R Markdown: https://people.ok.ubc.ca/jpither/modules/Symbols_markdown.html
```


```{r read_sites, echo=FALSE}
library(tidyverse)
library(ggplot2)
library(scales)
library(cowplot)
library(flextable)
library(officer)

source("./report/tables/Table1.R")


land_use <- data.frame(col1=c(1,2,3),col2=c(1,2,3))
land_use <- read.csv("./report/tables/GLPF site characteristics.csv")
names(land_use) <- c("Site name","Scale","USGS Site ID", "Lake","Abbreviation","Urban","Agriculture","Forest","Water/ Wetland","Impervious")
#land_use <- land_use %>% filter(!(Abbreviation %in% c("BK","CG")))
```


## Site selection

 Table \@ref(tab:landuse))
 






```{r landuse, echo= FALSE}
source("./Report/Tables/Table1.R")
table_1 <- make_table_1(land_use)
table_1 <- set_caption(table_1, "Table: (\\#tab:landuse) Land cover for sampling sites including small storm sewers and open channels (small scale), subwatersheds of the Milwaukee River (subwatershed scale), and tributaries of the Great Lakes (watershed scale).")
table_1
```

